### ISSUE TITLE
add a composer.json

### ISSUE THREAD

**Issue by lsmith77** [boxalino/boxalino-client-SDK-php#1]
see https://getcomposer.org
and https://packagist.org/packages/apache/thrift

**Comment by lsmith77** [comment]
any decision on this?

**Comment by lsmith77** [comment]
BTW it might also make sense to split the examples into a separate repository.

**Comment by sylvainpaillard** [comment]
Dear Mr. Smith,
Thank you for your request. Yes we are preparing it and it should be soon added.
For your requests, we do not use github as priority ticketing system for our customers. If you have any request you want a quick answer on, please contact us at the support e-mail of Boxalino (e-mail is simply support at our main .com domain)
Best regards,
Sylvain Paillard
